### ISSUE TITLE
Add password recovery support

### ISSUE THREAD

**Issue by joseluisq** [psiho/jsbench-me#21]
There is no way to recover a password account. It would be great this feature.

**Comment by dalisoft** [comment]
Oh, yes. Site forgot password was not working. As well as does not implemented Login/register forms correctly. Because of these bugs i created account and lost credentials. It's not good

**Comment by psiho** [comment]
since I decided to rewrite the whole thing I haven't fixed this fast enough but fixed passwords and account resets manually on request. Anyway, v1 is on the way, already rewritten and now working on bugfixes and new features. few things related to this are already fixed in non-published code:
- "forgot password" feature works after failed login (considering to make it always visible instead of waiting for failed login)
- I'll will move away from code verification to link verification so refreshing page while waiting for code validation will not be a problem anymore.
... this will make everything simpler and more reliable. After that, authorization with google/FB or similar would be the best thing and I'll look into that.
