### ISSUE TITLE
[Issue] Test rows do not resize according to number of lines of code

### ISSUE THREAD

**Issue by Venryx** [psiho/jsbench-me#23]
Test rows do not resize according to number of lines of code.

This is a problem because some of my tests have dozens of lines, and it's very annoying to be unable to see more than a small portion of it when browsing the tests' code.

For now, I'm solving the issue in "userland" by creating the following user-script:
```
// ==UserScript==
// @name        Test row height fixer (jsbench.me)
// @namespace   Violentmonkey/Tampermonkey Scripts
// @match       https://jsbench.me/
// ==/UserScript==

let style = document.createElement("style");
document.body.append(style);
style.innerHTML = `
.row-holder {
    height: auto;
    min-height: 150px;
    background: #fafafa; /* match color */
}
`;
```

I use the open-source [Violentmonkey extension](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag?hl=en) to apply the userscript, but [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en) or the like should work as well.

It would be nice if the fix were present in the website itself, however.

**Comment by psiho** [comment]
Thank you for a suggestion. At the moment, complete rewrite of the app to v1 is done and I'm considering all feature requests and bugs to add in that release, before publishing it.

About auto-expanding code-boxes... sometimes I'd like it and sometimes not. While I'm writing the code, it helps, but once all the tests are written and I move to running tests, I like them small to see all the results in one screen. Some huge cases (which are rare though) would also make the page scroll too much. 

I'm thinking of some compromise. Possibly to make a button to change from auto-expand mode of all boxes to small/medium/large. I wouldnt like to put this in each and every box individually. Too much clicking, want to keep it simple.

Second option would be to make every box bottom border draggable. UI would still be simple this way and you could set it up like you like. But again, it would require more clicks and would not be as elegant as auto-expand.

Since this also relates to other new features, I haven't decided yet. Any suggestions are welcome.

**Comment by Venryx** [comment]
> I'm thinking of some compromise. Possibly to make a button to change from auto-expand mode of all boxes to small/medium/large. I wouldnt like to put this in each and every box individually. Too much clicking, want to keep it simple.

That sounds good to me. I'd leave it in auto-expand mode, but the option to have limited-height boxes is good for those who want it.

**Comment by raineorshine** [comment]
As a low effort solution, I like the idea of manually resizable boxes. Then I have complete control over the size. That said, I do think the default could be larger.

It might be as simple as this:

```css
.CodeMirror {
    resize: vertical;
    overflow: auto !important;
}
``` 

https://stackoverflow.com/questions/13977276/codemirror-textarea-resizable-like-a-standard-textarea

**Comment by Venryx** [comment]
> As a low effort solution, I like the idea of manually resizable boxes. Then I have complete control over the size. That said, I do think the default could be larger.

I much prefer auto-expand sizing myself... (especially if the manual resizing does not persist between page loads)

Perhaps a persisting user setting between "Auto-expand", "Small", "Medium", and "Large" (with the latter three allowing for manual resizing of individual boxes) would work best.

**Comment by psiho** [comment]
> Or instead of those presets, perhaps just "Auto-expand" and "Manual", with "manual" having a second number setting choosing how many lines to start as.

I like this idea. So auto/manual or auto/large/medium/small with dragging and persistence on user level.

In general, idea is to please as much people and scenarios with as few clicks possible. Persistence is also the key here. If I prefer small boxes I don't want to load even other people's tests/boxes large. So persistance will definetly not go on suite/case level. It will go on user level and apply to ALL open boxes.
Now, user persistence  also has 2 possible persistence places. One is user account level and another one user browser level. Since I often open tests on mobile and on my laptop, I prefer to store this persistance in a cookie on browser level. That way my mobile can open small boxes and my PC big ones, without a click.

So, auto/manual and browser persistence of the setting will go in v1 for sure. Draggable size... I will see if I manage to squeeze that one too. I don't want any more delays to v1.

**Comment by psiho** [comment]
This is done for v1 which will be published soon. After some thinking, This is what I have decided to do  for this first upgrade:
- introduced new "settings" menu in top-right corner with (currently) only "code editor size" setting and 4 options: small, medium, large and auto.
- first 3 settings set height of code editor to 150, 250, 400 and last one automatically expands to fit code inside editors. Setting applies to all editors (setup, teardown, code,...). I wanted to avoid cluttered UI with separate setting for each editor.
- setting is saved per user/browser. I decided not to save this globaly in Cognito user data. This is mostly for mobile testers that will probably want different settings there and on larger screens.
Different (logged in) users on the same browser have their settings saved separately.  All others (non logged in users) share settings.

Code is designed in a way that it's really easy to let users chose custom height by typing it in or by dragging something, but I decided not to complicate at this time. To be honest, after using it awhile, I think most people will use small or auto. I think more important will be work on "collapsed" view suggested in #14 

This will be easily changed after feedback.

**Comment by psiho** [comment]
This feature is further improved. Actually I'm quite happy with simplicity and functionality of this now. Now (in v1 to be published soon) also manual resize is added using standard browser resize functionality, so CSS only! Each editor can be individually and manually dragged to resize. Each editor manually resized will override site setting above (small, medium, large, auto) so future changes of the setting will not affect it (will affect other editors not resized manually).

I decided not to store this data so it is session based. As soon as you refresh the page, or open  a new test case, editor sizes will go back to defaults (size defined in settings). So it is more of "editing tool", than "displaying" rule as I want to keep editor sizes consistent to all other users tuning the case.

**If you're interested to participate in testing this, let me know and I'll send you test link.** For now I don't want test links public as I don't have (yet) proper public test workflow.
