### ISSUE TITLE
login via GitHub or Google

### ISSUE THREAD

**Issue by mfulton26** [psiho/jsbench-me#34]
for easier signup I'd love to be able to use my GitHub account to sign in (or Google or something but preferably GitHub)

**Comment by psiho** [comment]
Thanks for the suggestion. I'm using AWS Cognito for user authorization and indeed it is relatively easy to implement this. I already investigated while working on v1 and it almost was included in that release. However, since I also migrated users to another Cognito pool I decided to keep it safe and postpone.

It's very high on my list since then. Just keep an eye on this issue and it will let you know when it is done. However, in the next few months, paid projects have priority.

**Comment by psiho** [comment]
AWS Cognito does not support Github login. And tbh, I'm a bit sick of AWS for small projects. V2 of JSBenchme will go to a completely different stack. I'm considering Clerk to replace Cognito, but it means this will again skip the next milestone, v1.2 as it would postpone it too much.

 But patching Cognito code before removing it does not make sense. Especially because DynamoDB will be replaced too, AWS Lambda and AWS API Gateway.... most probably with Nextjs / Postgres /Clerk.

So, I'm closing this. But functionality is planned for v2.
