### ISSUE TITLE
IE11 requires polyfills

### ISSUE THREAD

**Issue by KaelWD** [psiho/jsbench-me#9]
![image](https://user-images.githubusercontent.com/16421948/33723115-df65c700-dbbf-11e7-9a92-3902221084d5.png)

I recommend babel-polyfill.

**Comment by psiho** [comment]
To be honest, haven't even tested this in latest IE versions :) Thank you for noticing. I'll put it into next release ASAP together with other IE issues.

**Comment by psiho** [comment]
Polyfills fixed only part of the problem for MS browsers. Problem is with sandbox for test running and it will take me a few days till I have time to resolve this as it is not a small task.

Same is with issue #8 so I can call it a general MS browsers support. It's obviously on the top of my list because we simply have to support those browsers to make comparisons.

In the meantime, just use other browser :)

**Comment by psiho** [comment]
Finally support for MS browsers is added. I tested on Edge 40 and IE 11. It was not about polyfills only (but I added them too) but in a funny way IE deals with postMessage and sandboxed iframes.

I'd like to see reports of other, older, MS browsers.
